# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
project ‘nineKeyKeyboard.xcodeproj’

target 'nineKey' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  # Pods for nineKey

end

target 'nineKeyKeyboard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  # Pods for nineKeyKeyboard

end
