# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs'

platform :ios, ’10.0’
project ‘9-key.xcodeproj’

target ‘9-key’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftSocket'
  pod 'Alamofire', '~> 4.4'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  # Pods for 9-key

end

target ‘9-key-keyboard’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  # Pods for 9-key-keyboard

end
